name: 'Add Tag'
description: 'Add Tag to Existing GCloud Docker Artifact Image'
inputs:
  gcloud-workload-identity-provider:
    required: true
    description: 'GCloud Identity Provider id to use for federated authentication'
  gcloud-service-account:
    required: true
    description: 'GCloud Service Account to authenticate as, e.g. github-actions@...'
  gcloud-docker-image-url:
    required: true
    description: 'GCloud Docker Image Url'
  digest:
    description: 'Docker Image digest add tag to'
    required: true
  new-tag:
    description: 'Docker Image tag to add'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ inputs.gcloud-workload-identity-provider }}
        service_account: ${{ inputs.gcloud-service-account }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Add Tag
      run: |-
        gcloud container images add-tag \
        ${{ inputs.gcloud-docker-image-url }}@${{ inputs.digest }} \
        ${{ inputs.gcloud-docker-image-url }}:${{ inputs.new-tag }}
      shell: sh