name: 'Add Tag'
description: 'Add Tag to Existing GCloud Docker Artifact Image'
inputs:
  gcloud-project-id:
    description: 'Google Cloud Project Id'
    required: true
  gcloud-artifact-region:
    description: 'Region for Google Cloud Artifact'
    required: true
  gcloud-artifact-project:
    description: 'Project for Google Cloud Artifact'
    required: true
  gcloud-artifact-repository:
    description: 'Repository for Google Cloud Artifact'
    required: true
  gcloud-artifact-image:
    description: 'Artifact Image name for Google Cloud Artifact'
    required: true
  tag:
    description: 'Docker Image tag add tag to'
    required: true
  new-tag:
    description: 'Docker Image tag to add'
    required: true
  gcloud-workload-identity-provider:
    required: true
    description: 'GCloud Identity Provider id to use for federated authentication'
  gcloud-service-account:
    required: true
    description: 'GCloud Service Account to authenticate as, e.g. github-actions@...'
runs:
  using: "composite"
  steps:
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ inputs.gcloud-workload-identity-provider }}
        service_account: ${{ inputs.gcloud-service-account }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Add Tag
      run: |-
        gcloud container images add-tag \
        ${{ inputs.gcloud-artifact-region }}-docker.pkg.dev/${{ inputs.gcloud-artifact-project }}/${{ inputs.gcloud-artifact-repository }}/${{ inputs.gcloud-artifact-image }}:${{ inputs.tag }} \
        ${{ inputs.gcloud-artifact-region }}-docker.pkg.dev/${{ inputs.gcloud-artifact-project }}/${{ inputs.gcloud-artifact-repository }}/${{ inputs.gcloud-artifact-image }}:${{ inputs.new-tag }}
      shell: sh